services:
  web:
    build: .
    container_name: python-flask
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:5000"
    networks:
      - mynetwork
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - myvolume:/var/lib/mysql
    networks:
      - mynetwork 
    healthcheck:
      test: ["CMD", "mysql", "--user=${MYSQL_USER}", "--password=${MYSQL_ROOT_PASSWORD}", "--silent", "--execute", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure

volumes:
  myvolume:

networks:
  mynetwork:

