name: main branch pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true

  prep:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - id: vars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  build-push:
    uses: ./.github/workflows/reusable-docker.yml
    needs: [ prep,build-test ]
    with:
      image_name: ${{ github.event.repository.name }}
      tag: ${{ needs.prep.outputs.short_sha }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}
  

  security-deploy:
    runs-on: self-hosted        # runs on YOUR local machine
    needs: [build-push, prep]
    environment: environment
    steps:
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'your-username/your-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

      - name: Deploy with docker-compose
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Health check
        run: |
          sleep 10
          curl -sf http://localhost:8080/health || exit 1