name: main branch pipeline

on:
  push:
    branches: [master]

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true

  prep:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - id: vars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  build-push:
    uses: ./.github/workflows/reusable-docker.yml
    needs: [ prep,build-test ]
    with:
      image_name: ${{ github.event.repository.name }}
      tag: ${{ needs.prep.outputs.short_sha }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy: 
    runs-on: ubuntu-latest
    needs: [build-push, prep]
    environment: environment
    steps:
      - name: deploy message
        run: |  
          echo "Deploying image: ${{ secrets.DOCKER_USERNAME }}/github-actions-capstone:${{ needs.prep.outputs.short_sha }}"
      - name: environment info
        run: |
          echo "The environment being used is : ${{ vars.SITE }}"
      - name: success message
        if: success()
        run: echo "SUCCESSFULL"