name: pull requests pipeline
on: 
  pull_request:
    branches: [master]
    types: [ opened , synchronize]

jobs:
  pr-pipeline:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true
  pr-comment:
    runs-on: ubuntu-latest
    needs: pr-pipeline
    steps:
      - name: pr checks
        run: |
          echo "PR checks passed for branch: ${{ github.ref }}


